### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Offical_DTU_Dataset/Points/stl/ObsMask/ObsMask24_10.mat'

### ISSUE THREAD

**Issue by nwulq** [hbb1/2d-gaussian-splatting#39]
Thank you very much for your excellent work. I am new to this field and there is no problem with training and testing when reproducing your code. But when I run the full evaluation of DTU data, I get the following error：

mesh post processed saved at ./eval/dtu/scan122/train/ours_30000/fuse_post.ply
cull mesh ....
Culling mesh given masks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 49/49 [01:06<00:00,  1.37s/it]
masking data pcd:  44%|█████████████████████████████████████████████████████████████████████████████████████▊                                                                                                           | 4/9 [00:36<00:56, 11.31s/it]Traceback (most recent call last):
  File "/root/anaconda3/envs/surfel_splatting/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 39, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/dtu_eval/Offical_DTU_Dataset/Points/stl/ObsMask/ObsMask24_10.mat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/2d/scripts/eval_dtu/eval.py", line 98, in <module>
    obs_mask_file = loadmat(f'{args.dataset_dir}/ObsMask/ObsMask{args.scan}_10.mat')
  File "/root/anaconda3/envs/surfel_splatting/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/root/anaconda3/envs/surfel_splatting/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/root/anaconda3/envs/surfel_splatting/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/root/anaconda3/envs/surfel_splatting/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/dtu_eval/Offical_DTU_Dataset/Points/stl/ObsMask/ObsMask24_10.mat'
masking data pcd:  44%|█████████████████████████████████████████████████████████████████████████████████████▊                                                                                                           | 4/9 [00:36<00:45,  9.18s/it]
cull mesh ....

I downloaded the Points file based on the DTU point cloud you provided, but it only contains the STL ply file, without the ObsMask's ObsMaskxxx_10.mat and Planexxx.mat files. How can I solve this problem?

**Comment by hbb1** [comment]
Did you use sample set on the homepage, it should contain these information http://roboimagedata2.compute.dtu.dk/data/MVS/SampleSet.zip

**Comment by nwulq** [comment]
Sorry, I overlooked that the MVS data in the SampleSet comes with a mat file. Thank you very much, I have solved this problem😀

**Comment by nwulq** [comment]
I am very sorry to bother you again. I visualized fuse_post.ply in the scan24 case of DTU and found that it only rebuilt a part. What is the reason for this? The command I used is: python render.py -m /root/autodl-tmp/2d/eval/dtu/scan24 -s /root/autodl-tmp/DTU_ceshi/scan24 --skip_train --skip_test --depth_ratio 1.0 --num_cluster 1 --voxel_size 0.004 --sdf_trunc 0.016 --depth_trunc 3.0 -r 2
![sanwei](https://github.com/hbb1/2d-gaussian-splatting/assets/45096541/3b8dcbe6-dc38-4577-9dd5-399aea66a346)

**Comment by hbb1** [comment]
The backside of the room  is not captured by the images, so you cannot reconstruct it.

**Comment by nwulq** [comment]
Thank you very much for your answer. I have basically reproduced your work. Your work is excellent. Finally, please allow me to ask you another question. I generated a complete reconstruction model with background, and then converted it into STL file through meshlab. 
![微信截图_20240522170351](https://github.com/hbb1/2d-gaussian-splatting/assets/45096541/63433297-8081-4215-809c-4be66f074a5e)
How can I get a model without background, as shown in your picture (c).
![微信截图_20240522170431](https://github.com/hbb1/2d-gaussian-splatting/assets/45096541/41a5a0ed-51b0-42b1-bd44-2a9e10e0390a)

**Comment by lt-wang** [comment]
cy

**Comment by nwulq** [comment]
> cy

hi，what's meaning？
