### ISSUE TITLE
Error creating the environment (i.e. during installation)

### ISSUE THREAD

**Issue by pwernette** [hbb1/2d-gaussian-splatting#65]
The listed directions do not appear to work for creating the environment required for the code repo. When following the listed directions I'm receiving the same error (see below), regardless of whether I try to create it with WSL2 or Windows (bash):

```GitHub/2d-gaussian-splatting$ conda env create --file environment.yml
Retrieving notices: ...working... done
Channels:
 - pytorch
 - nvidia
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: | Ran pip subprocess with arguments:
['/home/miniconda3/envs/2dgs/bin/python', '-m', 'pip', 'install', '-U', '-r', '/mnt/d/OneDrive/Documents/GitHub/2d-gaussian-splatting/condaenv._75lxlp0.requirements.txt', '--exists-action=b']
Pip subprocess output:
Processing ./submodules/diff-surfel-rasterization
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/mnt/d/OneDrive/Documents/GitHub/2d-gaussian-splatting/submodules/diff-surfel-rasterization/setup.py", line 13, in <module>
          from torch.utils.cpp_extension import CUDAExtension, BuildExtension
        File "/home/miniconda3/envs/2dgs/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 25, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/miniconda3/envs/2dgs/lib/python3.8/site-packages/pkg_resources/__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

I've used subprocess extensively in the past without any issue for other projects.

**Comment by RongLiu-Leo** [comment]
Try:
```
pip install setuptools=69.0.0
```

**Comment by kajalsanklecha** [comment]
Does the error get solved by the above solution. Because I am still getting the same error. Any fix for this?

**Comment by hbb1** [comment]
can you print the full error message?

**Comment by kajalsanklecha** [comment]
`Processing ./submodules/diff-surfel-rasterization
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/ajnhawk/Documents/2d-gaussian-splatting/submodules/diff-surfel-rasterization/setup.py", line 13, in <module>
          from torch.utils.cpp_extension import CUDAExtension, BuildExtension
        File "/home/ajnhawk/anaconda3/envs/surfel_splatting/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 25, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/ajnhawk/anaconda3/envs/surfel_splatting/lib/python3.8/site-packages/pkg_resources/__init__.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

Above is the output for `pip install submodules/diff-surfel-rasterization`

While trying to run train.py, following is the error:

`Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "/home/ajnhawk/Documents/2d-gaussian-splatting/gaussian_renderer/__init__.py", line 14, in <module>
    from diff_surfel_rasterization import GaussianRasterizationSettings, GaussianRasterizer
ModuleNotFoundError: No module named 'diff_surfel_rasterization'`

**Comment by NinjaCats** [comment]
your need write setuptools==68.0.0 in environment.yml file at dependencies not pip to force reinstall setuptools
