### ISSUE TITLE
Render Mesh Error

### ISSUE THREAD

**Issue by zhqy513z** [hbb1/2d-gaussian-splatting#73]
(surfel_splatting) C:\Users\Zqy\2d-gaussian-splatting>python render.py -m C:\Users\Zqy\2d-gaussian-splatting\output\dengzi -s C:\Users\Zqy\2d-gaussian-splatting\data\dengzi --unbounded
Looking for config file in C:\Users\Zqy\2d-gaussian-splatting\output\dengzi\cfg_args
Config file found: C:\Users\Zqy\2d-gaussian-splatting\output\dengzi\cfg_args
Rendering C:\Users\Zqy\2d-gaussian-splatting\output\dengzi
Loading trained model at iteration 30000
Reading camera 1/207C:\Users\Zqy\anaconda3\envs\surfel_splatting\lib\site-packages\PIL\TiffImagePlugin.py:870: UserWarning: Corrupt EXIF data.  Expecting to read 2 bytes but only got 0.
  warnings.warn(str(msg))
Reading camera 207/207
Loading Training Cameras
[ INFO ] Encountered quite large input images (>1.6K pixels width), rescaling to 1.6K.
 If this is not desired, please explicitly specify '--resolution/-r' as 1
Loading Test Cameras
export training images ...
reconstruct radiance fields: 207it [00:04, 44.90it/s]
Traceback (most recent call last):
  File "render.py", line 62, in <module>
    gaussExtractor.reconstruction(scene.getTrainCameras())
  File "C:\Users\Zqy\anaconda3\envs\surfel_splatting\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Zqy\2d-gaussian-splatting\utils\mesh_utils.py", line 110, in reconstruction
    self.rgbmaps = torch.stack(self.rgbmaps, dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [3, 1035, 1600] at entry 0 and [3, 1060, 1600] at entry 13

**Comment by hbb1** [comment]
Seems like that your training set has images with different resolutions. You can store the rgbmap without stack.
